config/routes.rb
Rails.application.routes.draw do
  root "events#new"

  resources :events, only: [:new, :create, :show, :destroy]
  resources :sections, only: [:new, :create, :edit, :update, :destroy]
  resources :items, only: [:new, :create, :edit, :update, :destroy]

  get "/login", to: "sessions#login"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ApplicationRecord
  has_secure_password
  has_many :sections
  validates :name, presence: true, uniqueness: { case_sensitive: false }
  validates :password, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :section
  validates :item, presence: true
  validates :name, presence: true
end

app/models/section.rb
class Section < ApplicationRecord
  belongs_to :event
  has_many :items
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ApplicationHelper

  def authorize
    if !current_event
      flash[:notice] = "403: Access Denied"
      flash.keep
      redirect_to root_path
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authorize, only: [:show]
  before_action :set_event, only: %i[ destroy ]

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      session[:event_id] = @event.id
      redirect_to event_path(@event.id)
    else
      flash[:error] = "'#{@event.name}' is already taken!"
      flash.keep
      redirect_to root_path
    end
  end

  def show
    @event = Event.find(params[:id])
    @sections = Section.where("event_id = '#{@event.id}'").order("name ASC")
  end

  def destroy
    @sections = Section.where("event_id = '#{@event.id}'")
    @sections.each do |section|
      @items = Item.where("section_id = '#{section.id}'")
      @items.each do |item|
        item.destroy
      end
      section.destroy
    end
    @event.destroy

    respond_to do |format|
      format.html { redirect_to root_path, notice: "Event deleted" }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.required(:event).permit(:name, :password)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
    before_action :set_item, only: %i[ edit update destroy ]
  
    def new
      @item = Item.new(section_id_param)
    end
  
    def create
      @item = Item.new(item_params)
  
      respond_to do |format|
        if @item.save
          format.html { redirect_to event_path(current_event.id), notice: "Item created" }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @item.errors, status: :unprocessable_entity }
        end
      end
    end
  
    def edit
    end
  
    def update
      respond_to do |format|
        if @item.update(item_params)
          format.html { redirect_to event_path(current_event.id), notice: "Item updated" }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @item.errors, status: :unprocessable_entity }
        end
      end
    end
  
    def destroy
      @item.destroy
  
      respond_to do |format|
        format.html { redirect_to event_path(current_event.id), notice: "Item deleted" }
        format.json { head :no_content }
      end
    end
  
    private
  
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    def section_id_param
      params.permit(:section_id)
    end

    # Only allow a list of trusted parameters through.
    def item_params
      params.require(:item).permit(:item, :name, :section_id)
    end
  end
  

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  before_action :set_section, only: %i[ edit update destroy ]

  def new
    @section = Section.new
  end

  def create
    @section = Section.new(section_params)

    respond_to do |format|
      if @section.save
        format.html { redirect_to event_path(current_event.id), notice: "Section created" }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @section.update(section_params)
        format.html { redirect_to event_path(current_event.id), notice: "Section updated" }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @items = Item.where("section_id = '#{@section.id}'")
    @items.each do |item|
      item.destroy
    end
    @section.destroy

    respond_to do |format|
      format.html { redirect_to event_path(current_event.id), notice: "Section deleted" }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_section
    @section = Section.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def section_params
    params.require(:section).permit(:name, :event_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  require "bcrypt"

  def create
    @event = Event.find_by(name: params[:name])

    if !!@event && @event.authenticate(params[:password])
      session[:event_id] = @event.id
      redirect_to event_path(@event.id)
    else
      flash[:error] = "Incorrect username/password"
      flash.keep
      redirect_to login_path
    end
  end

  def destroy
    session[:event_id] = nil
    @event = nil
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def logged_in?
    !!session[:event_id]
  end

  def current_event
    @current_event ||= Event.find_by_id(session[:event_id]) if !!session[:event_id]
  end
end

app/views/events/new.html.erb
<div class="top">
    <div class="top_wrapper">
        Picnic
        <%= button_to "Log In", "/login", method: :get, :class => "button" %>
    </div>
</div>
<div class="wrapper">
  <% if flash[:notice] %>
    <div class="denied"><%= flash[:notice] %></div>
  <% end %>

  <div class="form_wrapper">
    <h1>Create New Event</h1>
    <%= form_for @event do |f| %>
        <%= f.text_field :name, placeholder: "Event Name" %><br>
        <%= f.password_field :password, placeholder: "Password" %><br>
        <% if flash[:error] %>
            <div class="error"><%= flash[:error] %></div>
        <% end %>
        <div class="submit_button">
          <%= f.submit "Create", :class => "button" %>
        </div>
    <% end %><br>
  </div>
</div>

app/views/events/show.html.erb
<div class="top">
    <div class="top_wrapper">
        Picnic
        <div class="button_wrapper">
          <%= button_to "Log Out", logout_path, method: :delete, :class => "button" %>
        </div>
    </div>
</div>
<div class="wrapper">
    <div class="home_title"><%= @event.name %></div>
    <div class="delete_wrapper">
      <%= button_to "Delete Event", "/events/#{@event.id}", method: :delete, :class => "danger_button" %>
    </div>
    <div class="notice"><%= notice %></div>
    
    <div id="sections">
      <% @sections.each do |section| %>
        <div class="section_wrapper">
          <div class="section_top">
            <div class="section_name"><%= section.name %></div>

            <div class="button_wrapper">
              <%= button_to "Edit", edit_section_url(section), method: :get, :class => "button" %>&nbsp;
              <%= button_to "Delete", "/sections/#{section.id}", method: :delete, :class => "danger_button" %>
            </div>
          </div>
          <% Item.where("section_id = '#{section.id}'").order("item ASC").each do |item| %>
            <div class="item_wrapper">
              <div class="item_contents">
                <%= item.item %><br>
                <div class="person">By: <%= item.name %></div>
              </div>

              <div class="button_wrapper">
                <%= button_to "Edit", edit_item_url(item), method: :get, :class => "button" %>&nbsp;
                <%= button_to "Delete", "/items/#{item.id}", method: :delete, :class => "danger_button" %>
              </div>
            </div>
          <% end %>
          <br><%= button_to "Add Item", new_item_path, method: :get, params: { :section_id => section.id }, :class => "button" %>
        </div>
      <% end %>
      <br><%= button_to "Add Section", new_section_path, method: :get, :class => "button" %>
    </div>
</div>
<div class="footer"></div>

app/views/items/_form.html.erb
<%= form_with(model: item) do |form| %>
  <div>
    <%= form.text_field :item, placeholder: "Item" %>
  </div>

  <div>
    <%= form.text_field :name, placeholder: "Person Name" %>
  </div>

  <div class="hidden">
    <%= form.text_field :section_id, value: item.section_id %>
  </div>

  <% if item.errors.any? %>
    <div class="error">
      <% item.errors.each do |error| %>
        <%= error.full_message %><br>
      <% end %>
    </div>
  <% end %>

  <div class="submit_button">
    <%= form.submit :id => "create", :class => "button" %>
  </div>
<% end %>

app/views/items/edit.html.erb
<div class="top">
    <div class="top_wrapper">
        Picnic
        <%= button_to "Home", event_path(current_event.id), method: :get, :class => "button" %>
    </div>
</div>
<div class="wrapper">
<div class="form_wrapper">
    <h1>Edit Item</h1>
    <%= render "form", item: @item %><br>
</div>
</div>

app/views/items/new.html.erb
<div class="top">
    <div class="top_wrapper">
        Picnic
        <%= button_to "Home", event_path(current_event.id), method: :get, :class => "button" %>
    </div>
</div>
<div class="wrapper">
<div class="form_wrapper">
    <h1>New Item</h1>
    <%= render "form", item: @item %><br>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Picnic</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "layout" %>
    <%= favicon_link_tag asset_path('cupcake.png') %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/sections/_form.html.erb
<%= form_with(model: section) do |form| %>
  <div>
    <%= form.text_field :name, placeholder: "Section Name" %>
  </div>

  <div class="hidden">
    <%= form.text_field :event_id, value: current_event.id %>
  </div>

  <% if section.errors.any? %>
    <div class="error">
      <% section.errors.each do |error| %>
        <%= error.full_message %><br>
      <% end %>
    </div>
  <% end %>

  <div class="submit_button">
    <%= form.submit :id => "create", :class => "button" %>
  </div>
<% end %>

app/views/sections/edit.html.erb
<div class="top">
    <div class="top_wrapper">
        Picnic
        <%= button_to "Home", event_path(current_event.id), method: :get, :class => "button" %>
    </div>
</div>
<div class="wrapper">
<div class="form_wrapper">
    <h1>Edit Section</h1>
    <%= render "form", section: @section %><br>
</div>
</div>

app/views/sections/new.html.erb
<div class="top">
    <div class="top_wrapper">
        Picnic
        <%= button_to "Home", event_path(current_event.id), method: :get, :class => "button" %>
    </div>
</div>
<div class="wrapper">
<div class="form_wrapper">
    <h1>New Section</h1>
    <%= render "form", section: @section %><br>
</div>
</div>